### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by 13386536068** [wz18207/azure_kinect_pcl_grabber#1]
1 debug or release?
2 My point cloud rendering is very slow in debug mode.
3 In relase mode, the application cannot be started normally, the problem of 0xc000007b.
Thanks!

**Comment by wz18207** [comment]
Thanks for contact.
For 2，I think you should do it in release side.
Sorry I don't know your problem. Could you send me screenshot of your problem.

**Comment by 13386536068** [comment]
Thank you for your answer. The screenshot of my problem is as follows. I installed DirectX according to the online solution, but it did not solve the problem. I don't know if you've had this problem before.
![problem](https://user-images.githubusercontent.com/46738286/89729707-e3b68680-da6a-11ea-8ea7-e9ab44de8532.png)

**Comment by wz18207** [comment]
Emmm, I believe you may to connect you hardware as running.

**Comment by 13386536068** [comment]
Thank you. I have solved this problem because my running environment is not configured properly in relase mode.
